require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.gitsigns"
require "user.nvim-tree"
require "user.bufferline"
require "user.evil-lualine"
require "user.alpha"
require "user.whichkey"
require "user.fidget"
require "user.vimtest"
require "user.comment"
require "user.noice"
require "user.nvim-remote"
require "user.toggleterm"
require "user.scrollbar"


-- require "user.project"
-- require "user.indentline"
-- require "user.autocommands"
-- require "user.nvim-ufo"
